### PR TITLE
Product save & publish feature

### PR DESCRIPTION
**Pull request by anantanant2015**
This would give user ability to publish his product from new product,
edit product page.

## Motivation and Context

- When creating a new product or editing any product, user should be able to
  publish the product.

## Describe your changes

- Adds js for new product ,adds publish helper and use
  helper function in new, edit js for product.
- Updates product controller to handle redirection publish
  option.
- Updates product form templates for save and publish feature.
- Updates redirect with updated conn to take only rummage params
  in product controller.

## Any further comments?

- While handling the redirection, params were required, so default rummage 
  application is removed and handled in redirect with updated conn method.

------

## Checklist

- [ ] I have read [CONTRIBUTING.md][contributing].
- [ ] My code follows the [style guidelines][contributing] of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code does not generate any (new) [`credo`][credo] and compile-time warnings.
- [ ] I have updated the documentation wherever necessary.
- [ ] I have added tests to cover my changes.

[contributing]: https://github.com/aviabird/snitch/CONTRIBUTING.md
[credo]: https://github.com/rrrene/credo

------
Dear Gatekeeper,

Please make sure that the commits that will be merged or rebased into the base
branch are [formatted according to our standards][commit-style].

> The only additional requirement is that the the PR number must appear in the
> commit title in brackets: `(#XXX)`

[commit-style]: https://github.com/aviabird/snitch/blob/develop/CONTRIBUTING.md#styling

### CODE REVIEW

**Comment by ashish173** [comment]
@SagarKarwande please review then when you get time.

**Comment by ashish173** [comment]
@kartikjagdale It always feels so good to see you in action. Cheers!

**Comment by ashish173** [comment]
@anantanant2015 you need to resolve this conflict so we can merge it?

**Comment by anantanant2015** [comment]
@ashish173 conflicts resolved

**Pull request merged**
